### ISSUE TITLE
`crux-llvm`: Fix compilation error on Windows

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#963]
`crux-llvm` currently fails to compile on Windows, as seen in [this CI job](https://github.com/GaloisInc/crucible/runs/6113020921?check_suite_focus=true#step:10:1334):

```
[1 of 2] Compiling RealMain         ( exe\windows\RealMain.hs, D:\\a\crucible\crucible\dist-newstyle\build\x86_64-windows\ghc-9.0.2\crux-llvm-0.5.0.99\x\crux-llvm\build\crux-llvm\crux-llvm-tmp\RealMain.o )

exe\windows\RealMain.hs:7:29: error:
Error:     • Couldn't match expected type: Maybe
                                      Crux.Config.Common.OutputOptions
                                    -> Crux.Log.OutputConfig CruxLLVMMain.CruxLLVMLogging
                  with actual type: IO
                                      (Maybe Crux.Config.Common.OutputOptions
                                       -> Crux.Log.OutputConfig CruxLLVMMain.CruxLLVMLogging)
    • In the first argument of ‘mainWithOutputConfig’, namely
        ‘defaultOutputConfig’
      In the first argument of ‘(>>=)’, namely
        ‘mainWithOutputConfig defaultOutputConfig’
      In the expression:
        mainWithOutputConfig defaultOutputConfig >>= exitWith
  |
7 | main = mainWithOutputConfig defaultOutputConfig >>= exitWith

  |                             ^^^^^^^^^^^^^^^^^^^
```

This was most likely introduced in a76d80daf645fa5935aabf62922f81ddd1485538 (but not caught by CI at the time).
