### ISSUE TITLE
`crux` fails to build with `aeson-2.0.*`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#881]
Trying to build `crux` with `aeson-2.0.0.0` or later will fail with the following errors:

<details>

```
[16 of 21] Compiling Crux.SVCOMP      ( src/Crux/SVCOMP.hs, /home/rscott/Documents/Hacking/Haskell/sandbox/crucible/dist-newstyle/build/x86_64-linux/ghc-8.10.4/crux-0.5.0.99/build/Crux/SVCOMP.o, /home/rscott/Documents/Hacking/Haskell/sandbox/crucible/dist-newstyle/build/x86_64-linux/ghc-8.10.4/crux-0.5.0.99/build/Crux/SVCOMP.dyn_o )

src/Crux/SVCOMP.hs:230:38: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k0 Yaml.Value’
      Expected type: HM.HashMap k0 Yaml.Value
        Actual type: Yaml.Object
    • In the second argument of ‘HM.lookup’, namely ‘o’
      In the expression: HM.lookup "format_version" o
      In a stmt of a 'do' block:
        _ <- case HM.lookup "format_version" o of
               Just (Yaml.String "2.0") -> return ()
               _ -> fail
                      $ unwords
                          ["Expected verification task version 2.0 while parsing", show fp]
    |
230 |   do case HM.lookup "format_version" o of
    |                                      ^

src/Crux/SVCOMP.hs:234:41: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k1 Yaml.Value’
      Expected type: HM.HashMap k1 Yaml.Value
        Actual type: Yaml.Object
    • In the second argument of ‘HM.lookup’, namely ‘o’
      In the expression: HM.lookup "input_files" o
      In a stmt of a 'do' block:
        fs <- case HM.lookup "input_files" o of
                Just v -> getStrs v
                Nothing
                  -> fail
                       $ unwords ["No 'input_files' section while parsing", show fp]
    |
234 |      fs <- case HM.lookup "input_files" o of
    |                                         ^

src/Crux/SVCOMP.hs:238:40: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k2 Yaml.Value’
      Expected type: HM.HashMap k2 Yaml.Value
        Actual type: Yaml.Object
    • In the second argument of ‘HM.lookup’, namely ‘o’
      In the expression: HM.lookup "properties" o
      In a stmt of a 'do' block:
        ps <- case HM.lookup "properties" o of
                Just v -> getProps v
                Nothing
                  -> fail
                       $ unwords ["No 'properties' section while parsing", show fp]
    |
238 |      ps <- case HM.lookup "properties" o of
    |                                        ^

src/Crux/SVCOMP.hs:242:39: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k3 Yaml.Value’
      Expected type: HM.HashMap k3 Yaml.Value
        Actual type: Yaml.Object
    • In the second argument of ‘HM.lookup’, namely ‘o’
      In the expression: HM.lookup "options" o
      In a stmt of a 'do' block:
        lang <- case HM.lookup "options" o of
                  Just v -> getLang v
                  Nothing
                    -> fail $ unwords ["No 'options' section while parsing", show fp]
    |
242 |      lang <- case HM.lookup "options" o of
    |                                       ^

src/Crux/SVCOMP.hs:269:47: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k6 Yaml.Value’
      Expected type: HM.HashMap k6 Yaml.Value
        Actual type: Yaml.Object
    • In the second argument of ‘HM.lookup’, namely ‘o’
      In the expression: HM.lookup "property_file" o
      In a stmt of a 'do' block:
        propf <- case HM.lookup "property_file" o of
                   Just (Yaml.String f) -> return (Text.unpack f)
                   _ -> fail
                          $ unwords
                              ["expected string value in 'property_file' while parsing", show fp]
    |
269 |    do propf <- case HM.lookup "property_file" o of
    |                                               ^

src/Crux/SVCOMP.hs:275:52: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k7 Yaml.Value’
      Expected type: HM.HashMap k7 Yaml.Value
        Actual type: Yaml.Object
    • In the second argument of ‘HM.lookup’, namely ‘o’
      In the expression: HM.lookup "expected_verdict" o
      In a stmt of a 'do' block:
        verdict <- case HM.lookup "expected_verdict" o of
                     Nothing -> return Nothing
                     Just (Yaml.Bool b) -> return (Just b)
                     Just (Yaml.String "true") -> return (Just True)
                     Just (Yaml.String "false") -> return (Just False)
                     Just _
                       -> fail
                            $ unwords
                                ["expected boolean value in 'expected_verdict' while parsing",
                                 show fp]
    |
275 |       verdict <- case HM.lookup "expected_verdict" o of
    |                                                    ^

src/Crux/SVCOMP.hs:290:30: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k4 Yaml.Value’
      Expected type: HM.HashMap k4 Yaml.Value
        Actual type: Yaml.Object
    • In the second argument of ‘HM.lookup’, namely ‘o’
      In the expression: HM.lookup "language" o
      In the expression:
        case HM.lookup "language" o of
          Just (Yaml.String "C") -> getCDataModel o
          Just (Yaml.String "Java") -> return Java
          _ -> fail
                 $ unwords
                     ["expected 'C' or 'Java' in 'language' while parsing", show fp]
    |
290 |    case HM.lookup "language" o of
    |                              ^

src/Crux/SVCOMP.hs:291:49: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Yaml.Value’
                     with ‘HM.HashMap k5 Yaml.Value’
      Expected type: HM.HashMap k5 Yaml.Value
        Actual type: Yaml.Object
    • In the first argument of ‘getCDataModel’, namely ‘o’
      In the expression: getCDataModel o
      In a case alternative: Just (Yaml.String "C") -> getCDataModel o
    |
291 |      Just (Yaml.String "C")    -> getCDataModel o
    |                                                 ^
```
</details>

This is because `aeson` replaces the `HashMap` field of `Object` with a [`KeyMap` type](https://hackage.haskell.org/package/aeson-2.0.1.0/docs/Data-Aeson-KeyMap.html#t:KeyMap). We should adjust the code accordingly.
