### PR TITLE
Make crucible:helper-tests compile with tasty-hspec-1.1.7 (#739)

### LINKED ISSUE #739: crucible:helper-tests fail to compile with tasty-hspec-1.1.7
`crucible`'s `helper-tests` fail to compile with the latest version of `tasty-hspec`:

```
$ cabal test crucible:helper-tests --constraint "tasty-hspec==1.1.7"
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - crucible-0.5 (test:helper-tests) (first run)
Preprocessing test suite 'helper-tests' for crucible-0.5..
Building test suite 'helper-tests' for crucible-0.5..
[1 of 1] Compiling Main             ( test/helpers/Main.hs, /home/rscott/Documents/Hacking/Haskell/sandbox/crucible/dist-newstyle/build/x86_64-linux/ghc-8.10.4/crucible-0.5/t/helper-tests/build/helper-tests/helper-tests-tmp/Main.o ) [Test.Tasty.Hspec changed]

test/helpers/Main.hs:20:11: error:
    Variable not in scope:
      describe
        :: [Char] -> t0 -> hspec-core-2.8.1:Test.Hspec.Core.Spec.Monad.Spec
   |
20 |           describe "panic" $
   |           ^^^^^^^^

test/helpers/Main.hs:21:11: error:
    • Variable not in scope: it :: [Char] -> t2 -> t0
    • Perhaps you meant ‘id’ (imported from Prelude)
   |
21 |           it "should throw an exception with the right details" $
   |           ^^

test/helpers/Main.hs:22:11: error:
    Variable not in scope:
      shouldThrow :: t1 -> (Panic Crucible -> Bool) -> t2
   |
22 |           shouldThrow (panic "Oh no!" ["line 1", "line 2"]) acceptableExn
   |           ^^^^^^^^^^^
```

On the other hand, they compile with earlier `tasty-hspec` releases, as `cabal test test:helper-tests --constraint "tasty-hspec==1.1.6"` works as you'd expect.

This happens because `tasty-hspec-1.1.7` no longer re-exports `Test.Hspec`. (These changes probably ought to have come with a major version bump, but oh well.) In any case, the fix is straightforward, so I'll submit it soon.

### PR DESCRIPTION
**Pull request by RyanGlScott**
`tasty-hspec-1.1.7` no longer re-exports `Test.Hspec` from `hspec`. In order to make `crucible`'s `helper-tests` work with all versions of `tasty-hspec`, this patch adds a `Test.Hspec` import. This also uses explicit imports from `Test.Tasty.Hspec` to ensure that there are no warnings when built with older versions of `tasty-hspec`.

Fixes #739.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
With this, the CI passes again, save for the macOS-specific failures observed in #741.
