### PR TITLE
crucible-go, ci: Adapt to recent Crux API changes, build in CI

### LINKED ISSUE #899: `exe:crucible-jvm` and `exe:crux-go` builds broken after f328d93
After f328d9320294f75c748c9f316ab09e4810a16d80, the `exe:crucible-jvm` build fails with:

```
$ cabal build exe:crucible-jvm
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - crucible-jvm-0.2 (exe:crucible-jvm) (file tool/Main.hs changed)
Preprocessing executable 'crucible-jvm' for crucible-jvm-0.2..
Building executable 'crucible-jvm' for crucible-jvm-0.2..
[2 of 2] Compiling Main             ( tool/Main.hs, /home/rscott/Documents/Hacking/Haskell/crucible/dist-newstyle/build/x86_64-linux/ghc-8.10.4/crucible-jvm-0.2/x/crucible-jvm/build/crucible-jvm/crucible-jvm-tmp/Main.o )

tool/Main.hs:178:50: error:
    Not in scope: type constructor or class ‘Crux.SimulatorCallback’
    Perhaps you meant ‘Crux.SimulatorCallbacks’ (imported from Crux)
    Neither ‘Crux’, ‘Crux.Config.Common’, ‘Crux.Log’,
            ‘Crux.Model’ nor ‘Crux.Types’ exports ‘SimulatorCallback’.
    |
178 | simulateJVM :: Crux.CruxOptions -> JVMOptions -> Crux.SimulatorCallback msgs
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^

tool/Main.hs:179:26: error:
    Not in scope: data constructor ‘Crux.SimulatorCallback’
    Perhaps you meant one of these:
      ‘Crux.SimulatorCallbacks’ (imported from Crux),
      variable ‘Crux.getSimulatorCallbacks’ (imported from Crux)
    Neither ‘Crux’, ‘Crux.Config.Common’, ‘Crux.Log’,
            ‘Crux.Model’ nor ‘Crux.Types’ exports ‘SimulatorCallback’.
    |
179 | simulateJVM copts opts = Crux.SimulatorCallback $ \sym _maybeOnline -> do
    |                          ^^^^^^^^^^^^^^^^^^^^^^
```

cc @langston-barrett

### PR DESCRIPTION
**Pull request by langston-barrett**
:crossed_fingers: for a green CI build on the first try

Fixes #899, #888

### CODE REVIEW

**Review by RyanGlScott — APPROVED** [review]
If it builds, ship it.

**Comment by langston-barrett** [comment]
Well, it doesn't build quite yet:
```
src/Language/Go/Parser.hs:199:50: error:
Error:     • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HM.HashMap k0 Value’
      Expected type: HM.HashMap k0 Value
        Actual type: Object
    • In the second argument of ‘HM.lookup’, namely ‘v’
      In the expression: HM.lookup "value" v
      In the expression:
        case HM.lookup "value" v of
          Just (Object v')
            -> case HM.lookup "type" v' of
                 Just "IOTA"
                   -> return $ IdentExpr pos go_tp Nothing $ Ident IdentNoKind "IOTA"
                 _ -> IdentExpr pos go_tp <$> v .:? "qualifier" <*> v .: "value"
          _ -> fail ""
    |
199 |           "identifier" -> case HM.lookup "value" v of
    |                                                  ^

src/Language/Go/Parser.hs:200:55: error:
Error:     • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HM.HashMap k1 a0’
      Expected type: HM.HashMap k1 a0
        Actual type: Object
    • In the second argument of ‘HM.lookup’, namely ‘v'’
      In the expression: HM.lookup "type" v'
      In the expression:
        case HM.lookup "type" v' of
          Just "IOTA"
            -> return $ IdentExpr pos go_tp Nothing $ Ident IdentNoKind "IOTA"
          _ -> IdentExpr pos go_tp <$> v .:? "qualifier" <*> v .: "value"
    |
200 |             Just (Object v') -> case HM.lookup "type" v' of
    |                                                       ^^
```
I remember seeing something about Aeson on this repo recently, I'll try to see if I can find some fixes and reproduce them in the context of `crucible-go`.

**Comment by langston-barrett** [comment]
Ah, this is #888.

**Comment by RyanGlScott** [comment]
Oof, I forgot about that. Luckily, there are some in-flight patches in GaloisInc/golang#3 and GaloisInc/golang#4 which should help here.

**Comment by langston-barrett** [comment]
Current failure should be fixed by https://github.com/GaloisInc/golang/pull/5
