### ISSUE TITLE
`exe:crucible-jvm` and `exe:crux-go` builds broken after f328d93

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#899]
After f328d9320294f75c748c9f316ab09e4810a16d80, the `exe:crucible-jvm` build fails with:

```
$ cabal build exe:crucible-jvm
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - crucible-jvm-0.2 (exe:crucible-jvm) (file tool/Main.hs changed)
Preprocessing executable 'crucible-jvm' for crucible-jvm-0.2..
Building executable 'crucible-jvm' for crucible-jvm-0.2..
[2 of 2] Compiling Main             ( tool/Main.hs, /home/rscott/Documents/Hacking/Haskell/crucible/dist-newstyle/build/x86_64-linux/ghc-8.10.4/crucible-jvm-0.2/x/crucible-jvm/build/crucible-jvm/crucible-jvm-tmp/Main.o )

tool/Main.hs:178:50: error:
    Not in scope: type constructor or class ‘Crux.SimulatorCallback’
    Perhaps you meant ‘Crux.SimulatorCallbacks’ (imported from Crux)
    Neither ‘Crux’, ‘Crux.Config.Common’, ‘Crux.Log’,
            ‘Crux.Model’ nor ‘Crux.Types’ exports ‘SimulatorCallback’.
    |
178 | simulateJVM :: Crux.CruxOptions -> JVMOptions -> Crux.SimulatorCallback msgs
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^

tool/Main.hs:179:26: error:
    Not in scope: data constructor ‘Crux.SimulatorCallback’
    Perhaps you meant one of these:
      ‘Crux.SimulatorCallbacks’ (imported from Crux),
      variable ‘Crux.getSimulatorCallbacks’ (imported from Crux)
    Neither ‘Crux’, ‘Crux.Config.Common’, ‘Crux.Log’,
            ‘Crux.Model’ nor ‘Crux.Types’ exports ‘SimulatorCallback’.
    |
179 | simulateJVM copts opts = Crux.SimulatorCallback $ \sym _maybeOnline -> do
    |                          ^^^^^^^^^^^^^^^^^^^^^^
```

cc @langston-barrett

**Comment by langston-barrett** [comment]
`crucible-jvm` is fixed, I'll do `crucible-go` next
