### ISSUE TITLE
what4 does not build with ghc 8.4.3

### ISSUE THREAD

**Issue by yav** [GaloisInc/crucible#60]
As of 2b2ac00f61a8643ce0c61d1afbf071a9a2beab56 `what4`  fails to build (ghc 8.4.3) with a bunch of type errors in `Builder`.  For example:

```
src/What4/Expr/Builder.hs:4479:20: error:
    • Could not deduce: ((w1 + 1) GHC.TypeNats.<=? w) ~ 'True
        arising from a use of ‘bvZext’
      from the context: 1 <= w
        bound by the type signature for:
                   integerToBV :: forall (w :: GHC.Types.Nat).
                                  (1 <= w) =>
                                  ExprBuilder t st
                                  -> SymInteger (ExprBuilder t st)
                                  -> NatRepr w
                                  -> IO (SymBV (ExprBuilder t st) w)
        at src/What4/Expr/Builder.hs:4473:3-13
      or from: (BaseIntegerType ~ 'BaseIntegerType, 1 <= w1)
        bound by a pattern with constructor:
                   BVToInteger :: forall (w :: GHC.Types.Nat) (e :: BaseType -> *).
                                  (1 <= w) =>
                                  e (BaseBVType w) -> App e BaseIntegerType,
                 in a pattern binding in
                      pattern guard for
                      an equation for ‘integerToBV’
        at src/What4/Expr/Builder.hs:4477:13-25
      or from: w ~ (w1 + (y + 1))
        bound by a pattern with constructor:
                   NatLT :: forall (y :: GHC.Types.Nat) (m :: GHC.Types.Nat).
                            NatRepr y -> NatComparison m (m + (y + 1)),
                 in a case alternative
        at src/What4/Expr/Builder.hs:4479:9-15
    • In the expression: bvZext sym w r
      In a case alternative: NatLT _ -> bvZext sym w r
      In the expression:
        case compareNat (bvWidth r) w of
          NatLT _ -> bvZext sym w r
          NatEQ -> return r
          NatGT _ -> bvTrunc sym w r
    • Relevant bindings include
        r :: Expr t (BaseBVType w1)
          (bound at src/What4/Expr/Builder.hs:4477:25)
        w :: NatRepr w (bound at src/What4/Expr/Builder.hs:4473:22)
        integerToBV :: ExprBuilder t st
                       -> SymInteger (ExprBuilder t st)
                       -> NatRepr w
                       -> IO (SymBV (ExprBuilder t st) w)
          (bound at src/What4/Expr/Builder.hs:4473:3)
     |
4479 |         NatLT _ -> bvZext sym w r
     |                    ^^^^^^^^^^^^^^
```

**Comment by yav** [comment]
Ah, yes, thanks!
